name:                warp-hello-world
version:             0.1.0.0
github:              "shaun-whitely/warp-hello-world"
license:             BSD3
author:              "Shaun Whitely"
maintainer:          "example@example.com"
copyright:           "2019 Shaun Whitely"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/warp-hello-world#readme>

dependencies:
- base >= 4.7 && < 5
- wai
- warp
- aeson
- text
- http-types
- mtl
- postgresql-simple
- resource-pool
- lens

library:
  source-dirs: src

executables:
  warp-hello-world-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - warp-hello-world

tests:
  warp-hello-world-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - warp-hello-world
